remote_theme: chrisbobbe/jekyll-theme-prologue
name: Yuri Gladkov
markdown: kramdown
url: https://cyberglad.github.io
base_url: https://cyberglad.github.io
collections: [sections]
avatar: http://files.softicons.com/download/android-icons/sugar-icons-by-snobawm/ico/googledrive.ico
permalink: /blog/:year/:month/:day/:title
