remote_theme: chrisbobbe/jekyll-theme-prologue
name: Yuri Gladkov
collections: [sections]
baseurl: https://cyberglad.github.io 
url: https://cyberglad.github.io
avatar: http://files.softicons.com/download/android-icons/sugar-icons-by-snobawm/ico/googledrive.ico
permalink: /blog/:year/:month/:day/:title
title: Not Working
subtitle: for software which is not working
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Yuri Gladkov
email: your-email@example.com
