remote_theme: chrisbobbe/jekyll-theme-prologue
name: Yuri Gladkov
collections: [sections]
avatar: http://files.softicons.com/download/android-icons/sugar-icons-by-snobawm/ico/googledrive.ico
permalink: /blog/:year/:month/:day/:title
title: Not Working
subtitle: for software which is not working
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Yuri Gladkov
email: your-email@example.com

# You'll want to customize url and baseurl for your own site:
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://cyberglad.github.io" # the base hostname & protocol for your site

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
